### ISSUE TITLE
Change line length to 120 chars

### ISSUE THREAD

**Issue by spencergibb** [spring-io/spring-javaformat#100]
It would be nice to have an option to set line length, say to 120

**Comment by philwebb** [comment]
I'm really not keen to add too many configuration options, it undermines the point of the project. If the current wrap length really isn't suitable then perhaps we should reconsider it across the board and all move to 120 chars.

**Comment by spencergibb** [comment]
Are there options?

We, as a team (Spring Cloud Core), want to use this (and are currently using it) and have a line length > 90.

**Comment by philwebb** [comment]
Currently pretty much nothing is configurable with the formatter. That was an intentional decision because I want to bring consistency to all the projects that use it. If we start adding flags for various options it undermines the point a little.

Line wrapping seems to be a contentious issue. I took the lead from https://github.com/spring-projects/spring-framework/wiki/Code-Style#line-wrapping and kept the limit small.

I personally quite like the smaller line length, but I'm not against changing it we can somehow manage to reach agreement that 120 is better than the current size.

**Comment by spencergibb** [comment]
I doubt there will ever be consensus. I guess we can always fork.

**Comment by philwebb** [comment]
I'd rather add an option than fork. I'm just not sure where it can go. We've got a copyright header year that is configurable so I guess it could go next to that. It'll be a bit clunky.

**Comment by philwebb** [comment]
Rather than make the limit totally configurable I'd be tempted to just support `default` and `wide` as options.

**Comment by spencergibb** [comment]
Yeah, that would probably be fine

**Comment by philwebb** [comment]
I've spend a couple of days on this (https://github.com/philwebb/spring-javaformat/tree/gh-100). It turns out making the length change is easy, adding build plugin configuration isn't too bad but getting the IDE's to find that value is very difficult.

We've discussed line length again on the Boot call and we think the best option is just to make 120 the default (if it means more people will adopt the formatter). We'll probably keep javadoc at 90.

**Comment by nasreddineskandrani** [comment]
Some dev are using other values and have to create a custom formatter on top of yours to be able to edit line length which is on my opinion a sign of "something is wrong".

Working with prettier for a decade and his popularity is so huge in frontend => not one never compain about having this option editable... 
i really suggest to reconsider your opinion on not making this field editable for spring project... it's just opinions... let people free : )

Thank you

**Comment by philwebb** [comment]
@nasreddineskandrani I really would have liked to made this one specific thing an option, but after a couple of days trying it just ended up consuming too much time. It's hard to find enough hours in the day to do all the things :(

**Comment by nasreddineskandrani** [comment]
From my participation in the open source world, i see often "help wanted" tag in repos. Which means if someone is open to do it he can open a PR so you'll out source the job and you can then only review the work as core members which is less time consuming.

If it's a matter of availibility your side. Can we tag this issue as 'Help Wanted' so someone may try to help you. I can't promess i will do it but i am sure someone will try it if he really wants the feature.

**Comment by philwebb** [comment]
@nasreddineskandrani Sure, feel free to open another issue (since the 120 change is done) and I'll tag it.
