### ISSUE TITLE
When using Gradle, upgrading from 0.0.15 to 0.0.17 results in unexpected formatting changes

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-javaformat#161]
I think this is Gradle-specific so it may have been caused by #148. Upgrading to 0.0.17 (from 0.0.15) results in some unexpected changes in formatting:

- Javadoc line width is narrowed
- The description for javadoc `@param` tags is split onto a separate line:
```
 * @param name
 *            name of the library
```
- `catch` is moved onto the same line as the closing `}` of the `try` block
```
} catch (IOException ex) {
```

**Comment by ttddyy** [comment]
I started applying spring-javafomat plugin to our library yesterday, and noticed `@param` behavior too.
It would be appreciated to decide either fix this or go with this change going forward. So that, I can decide whether to use 0.0.17 or 0.0.15 to our code base.
I'd like to be consistent in our code style with spring-boot since my library is built on top of spring-boot; so code-style consistency is nice to have.
