### ISSUE TITLE
Eclipse plugin error during build

### ISSUE THREAD

**Issue by cirelli94** [spring-io/spring-javaformat#177]
I set up spring-javaformat plugin with even the Checkstyle.
When I run build it says:

```
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'timebank-api'.
java.lang.NullPointerException
```

**Comment by wilkinsona** [comment]
Can you please share the stack trace of the `NullPointerException`. I think you should be able to find it in Eclipse's error log (Window -> Show View -> Error Log).

**Comment by cirelli94** [comment]
Here is the log: [Untitled.log](https://github.com/spring-io/spring-javaformat/files/4280154/Untitled.log)

**Comment by wilkinsona** [comment]
Thanks. The failures all appear to be coming from Checkstyle's Eclipse plugin. Given that Spring Java Format's Checkstyle integration works fine on the command line, I suspect that the problem is in Checkstyle's Eclipse plugin rather than any of the code that's maintained here. Please open an issue against that project and comment here with a link to it. We can re-open this issue if it turns out that some changes to Spring Java Format are needed after all.

**Comment by cirelli94** [comment]
Here is the linked bug on checkstyle: https://github.com/checkstyle/eclipse-cs/issues/217
Thanks for your support @wilkinsona

**Comment by wilkinsona** [comment]
Thanks for opening the other issue. I've subscribed to it. It would probably help them to diagnose the problem if you could share some more details about your Eclipse installation and the versions of the plugins that are involved.

**Comment by cirelli94** [comment]
I agree, and I did it, thanks for the tip.
