### ISSUE TITLE
Allow to Configure Formatting

### ISSUE THREAD

**Issue by rwinch** [spring-io/spring-javaformat#182]
I understand that the [README](https://github.com/spring-io/spring-javaformat/tree/c750ba6a806839bbe6cd78dff2622815eeb5ee77#what-is-this) states:

> Since the aim of this project is to provide consistency, each plugin is not generally configurable

However, that isn't realistic since each Spring team has different code style. I'd love to be able to use this project for the security related projects, but it really isn't practical until we can configure the plugin to meet our conventions.

**Comment by philwebb** [comment]
I did try to add configuration support for configurable line lengths at one point, but it turned out to be very difficult to even do that. See [this comment](https://github.com/spring-io/spring-javaformat/issues/100#issuecomment-486328273) for context.

Which parts of the configuration would need tweaking for Spring Security?

**Comment by rwinch** [comment]
I'd need to review in more detail, but for one we don't use Mockito's BDD statements.

**Comment by philwebb** [comment]
Those are checkstyle rules and should be much easier to configure than the formatting. In fact, I think it's possible already. I think you can copy/paste [these rules](https://github.com/spring-io/spring-javaformat/blob/master/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml) rather than importing `io.spring.javaformat.checkstyle.SpringChecks`.

**Comment by philwebb** [comment]
I also have some experience migrating projects to use the BDDMockito, so if it's a time constraint rather than a philosophical objection, let me know and I'll try to help.

**Comment by wilkinsona** [comment]
@rwinch Given that Security has now successfully adopted Spring Java Format, do you still have a need for the formatter to be more configurable?

**Comment by rwinch** [comment]
Thanks. This can be closed now
