### ISSUE TITLE
Requiring LF line separators isn't Windows-friendly

### ISSUE THREAD

**Issue by bedla** [spring-io/spring-javaformat#202]
Hi, 
I found that when I run build of `spring-javaformat` (or any project that uses this tool) on Windows with `autocrlf=false` it fails on camparations between `CRLF` and `LF`.
I think (from my experiment when I was preparing PR) that pass `lineSeparator` parametr to formatter is easy but what is hard is how to detect eg. from Maven that user is on Windows and uses `autocrlf=false`.
There is also `line.separator` system property, but is hard to assign from IDEA/Maven.
It seems that how formatter and `autocrlf` works it is not possible to set it to `false` and make it work on Windows. This means that projects (eg. spring-cloud-sleuth) that use this formatter won't work correctly when user clones repository with `core.autocrlf=false` global Git configuration.
Am I right?
Thx,
Ivos

**Comment by wilkinsona** [comment]
From what I have seen, it won’t just be the formatter that will have problems with line endings on Windows if you use `autocrlf=false`. We use `autocrlf=true` in Spring Boot’s Windows CI and don’t have any problems. What is your reason for disabling `autocrlf`?

**Comment by bedla** [comment]
I have `autocrlf=false` as global config because of some long (I even dont remember why) ago issue with Git and line-ending handling. Maybe I can remove it at my local env, I will investigate it... thx.

Anyways what I have found is, when sources are checked out with `LF` and formatter runs on Windows reformatted code has line endings that comes from `org.eclipse.jdt.internal.compiler.util.Util#LINE_SEPARATOR` constant. 
I think that this glitch should be documented somehow (maybe here or at spring-cloud docs). What do you think?
Thank you

**Comment by wilkinsona** [comment]
We've just hit a problem similar to this when upgrading the Spring Initializr project to Checkstyle 8.32. Spring Java Format currently requires `LF` line endings:

https://github.com/spring-io/spring-javaformat/blob/5e076802527b8dc13a14c08f20f510ee2aeec9aa/src/checkstyle/checkstyle.xml#L12

As mentioned above, we use `autocrlf=true` in our Windows CI pipelines to ensure that `LF` line endings in the repository are converted to `CRLF` line endings on the filesystem. This should have caused Checkstyle to report line ending violations but it did not due to a [bug](https://github.com/checkstyle/checkstyle/issues/4074) where it only checked the last byte of the line and therefore didn't notice that an `LF` line ending was in fact a `CRLF` line ending.

Checkstyle defaults to `LF_CR_CRLF` which matches `LF`, `CR`, or `CRLF`. We could switch to that. Alternatively we could use `SYSTEM` which matches whatever `System.getProperty("line.separator")` returns.

**Comment by philwebb** [comment]
I've dropped the attribute so the default of `LC_CR_CRLF` will be used.
