### ISSUE TITLE
Upgrade to Eclipse 2021-09

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#277]

**Comment by quaff** [comment]
Eager for this, It block me using `spring-javaformat`.

**Comment by wilkinsona** [comment]
Let's just straight to 2021-08 which has built-in support for Java 17.

**Comment by wilkinsona** [comment]
As part of this, we need to revisit the fix for #262 as the `System.getProperty` call [is now done in a lambda rather than an anonymous insert class](https://git.eclipse.org/c/equinox/rt.equinox.framework.git/commit/bundles/org.eclipse.osgi/supplement/src/org/eclipse/osgi/util/NLS.java?id=ba6205dab1f857fe87cf5985f03c1b5e88797064).

**Comment by wilkinsona** [comment]
I have a local build that works with 2021-09. Unfortunately, 2021-09 contains [a regression](https://bugs.eclipse.org/bugs/show_bug.cgi?id=576152) that causes 4 erroneous compilation failures in Spring Boot's buildpack platform module due to a method reference referring to an overloaded method. We may just have to live with those for now. Alternatively, changing the method references to lambda expressions appeases JDT's compiler.

**Comment by wilkinsona** [comment]
This upgrade is going to be problematic. The version of Eclipse JDT in 2021-09 appears to have been built with Java 11 so projects with a Java 8 baseline will have to jump through some hoops to continue to use newer versions of the formatter.

**Comment by wilkinsona** [comment]
2021-09 makes some changes to the wrapping of annotation attributes. The following two diffs are from running `format` against Spring Boot's main branch:

```diff
-@SpringBootTest(properties = "spring.main.web-application-type=reactive", classes = {
-               WebTestClientSpringBootTestIntegrationTests.TestConfiguration.class, ExampleWebFluxApplication.class })
+@SpringBootTest(properties = "spring.main.web-application-type=reactive",
+               classes = { WebTestClientSpringBootTestIntegrationTests.TestConfiguration.class,
+                               ExampleWebFluxApplication.class })
```

```diff
-@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT, properties = { "spring.jersey.type=filter",
-               "server.servlet.context-path=/app", "server.servlet.register-default-servlet=true" })
+@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT,
+               properties = { "spring.jersey.type=filter", "server.servlet.context-path=/app",
+                               "server.servlet.register-default-servlet=true" })
```

**Comment by wilkinsona** [comment]
I was mistaken [above](https://github.com/spring-io/spring-javaformat/issues/277#issuecomment-923725871). Java 17 support isn't built into 2021-09, but [is available as an add-on from the Marketplace](https://marketplace.eclipse.org/content/java-17-support-eclipse-2021-09-421). The add-on requires 2021-09.

JDT in 2021-06 has Java 8-level class files so it avoids some of the complications of 2021-09, but doesn't give us access to Java 17 support.

**Comment by wilkinsona** [comment]
A version built against 2021-06 seems to work fine in 2021-09 so that seems like a better short-term bet. I've opened https://github.com/spring-io/spring-javaformat/issues/286 for that. I think we should revert the 2021-09 upgrade for now.

**Comment by philwebb** [comment]
I attempted to force a bytecode downgrade using cglib. It didn't go well. I think we'll need to branch the code and have a java 11 specific release.
