### ISSUE TITLE
SpringHeaderCheck does not match against a regular expression in the header file

### ISSUE THREAD

**Issue by davesahil** [spring-io/spring-javaformat#303]
I am trying to use a header file like this one:

```java
/*
 * Copyright © ([20\d\d]) XYZ
 * This software and all information contained therein is confidential and proprietary
 * and shall not be duplicated, used, disclosed or disseminated in any way except as authorized
 * by the applicable license agreement, without the express written permission of XYZ.
 * All authorized reproductions must be marked with this language.
 */
```

to match against the headers on source files. But it does not work until I remove the regex in the header file and use literal year like 2021.

My checkstyle.xml looks like this:

```xml
<module name="com.puppycrawl.tools.checkstyle.Checker">
    <module name="io.spring.javaformat.checkstyle.SpringChecks">
        <property name="severity" value="warning"/>
        <property name="headerFile" value="checkstyle.header"/>
        <property name="excludes" value="io.spring.javaformat.checkstyle.check.SpringAvoidStaticImportCheck"/>
        <property name="excludes" value="io.spring.javaformat.checkstyle.check.SpringImportOrderCheck"/>
        <!--        <property name="excludes" value="io.spring.javaformat.checkstyle.check.SpringNoThisCheck"/>-->
    </module>
    <module name="io.spring.javaformat.checkstyle.check.SpringHeaderCheck">
        <property name="headerCopyrightPattern" value="[20\d\d]"/>
        <property name="headerFile" value="checkstyle.header"/>
    </module>
</module>
```

**Comment by wilkinsona** [comment]
Rather than including the pattern directly in the header file, you should use `${copyright-pattern}` as we do in the Apache 2 header:

https://github.com/spring-io/spring-javaformat/blob/84dcece4f3dd141d4acadef84627cddb3db71289/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/check/header-apache2.txt#L2

`${copyright-pattern}` is then replaced using the value of `headerCopyrightPattern` with appropriate escaping when the file's loaded:

https://github.com/spring-io/spring-javaformat/blob/84dcece4f3dd141d4acadef84627cddb3db71289/spring-javaformat/spring-javaformat-checkstyle/src/main/java/io/spring/javaformat/checkstyle/check/SpringHeaderCheck.java#L213

**Comment by davesahil** [comment]
> Rather than including the pattern directly in the header file, you should use `${copyright-pattern}` as we do in the Apache 2 header:
> 
> https://github.com/spring-io/spring-javaformat/blob/84dcece4f3dd141d4acadef84627cddb3db71289/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/check/header-apache2.txt#L2
> 
> `${copyright-pattern}` is then replaced using the value of `headerCopyrightPattern` with appropriate escaping when the file's loaded:
> 
> https://github.com/spring-io/spring-javaformat/blob/84dcece4f3dd141d4acadef84627cddb3db71289/spring-javaformat/spring-javaformat-checkstyle/src/main/java/io/spring/javaformat/checkstyle/check/SpringHeaderCheck.java#L213
> 
> If this doesn't work for you and you'd like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

This worked like a charm.

Thank you for the help!
